server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elastic_job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#Custom Config
zookeeper:
  address: localhost:2181
  namespace: elastic-job
  connectionTimeout: 10000
  sessionTimeout: 10000
  maxRetries: 3
simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=beijing,1=shanghai,2=changchun,3=changsha,4=hangzhou
  jobParameter: source1=public,source2=private
  failover: true
  monitorExecution: true
  monitorPort: 8889
  maxTimeDiffSeconds: -1
  jobShardingStrategyClass: com.dangdang.ddframe.job.lite.api.strategy.impl.AverageAllocationJobShardingStrategy
dataflowJob :
  cron: 0/10 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=beijing,1=shanghai